### PR TITLE
Fixed #217, Updates framework exception severity levels and uses ServiceExceptions

### LINKED ISSUE #217: Use correct framework event severity and exception types for service factory errors
Review the severity used when sending framework events. At least in the service factory area, we are sending warnings instead of errors.

Also we use `std::logic_error` instead of the existing `ServiceException` class when transporting exceptions via a framework event.

### PR DESCRIPTION
**Pull request by achristoforides**
This PR addresses issue #217 which requested a review of framework exception severity and usage of the already-existing ServiceException class in lieu of std::logic_error as stated by the spec.

By looking through the docs for OSGi, I identified the proper exception types and modified the currently used exceptions in the code. The same was done for std::logic_errors in the correct areas to better match the spec as well.

Two tests (BundleTest and ServiceFactoryTest) had to be updated to reflect the newly introduced state into the software's internal logic. For both tests, it was a matter of updating the type of exceptions or expected exception messages so that they matched the source code changes made.

### CODE REVIEW

File: framework/src/service/ServiceReferenceBasePrivate.cpp [hunk 1]
```diff
@@ -100,11 +102,13 @@ InterfaceMapConstPtr ServiceReferenceBasePrivate::GetServiceFromFactory(
...
   } catch (...) {
     s.reset();
+    std::string message = "ServiceFactory threw an unknown exception.";
     registration->bundle->coreCtx->listeners.SendFrameworkEvent(
       FrameworkEvent(FrameworkEvent::Type::FRAMEWORK_ERROR,
                      MakeBundle(bundle->shared_from_this()),
-                     std::string("ServiceFactory threw an unknown exception."),
-                     std::current_exception()));
+                     message,
+                     std::make_exception_ptr(ServiceException(message,
```
Comment (jeffdiclemente) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: Since an exception was thrown, we want to preserve the exception message and use that string as the ```message``` in the ```ServiceException``` object. Otherwise we are losing information which may be useful to users.

File: framework/src/service/ServiceReferenceBasePrivate.cpp [hunk 2]
```diff
@@ -278,10 +282,11 @@ bool ServiceReferenceBasePrivate::UngetPrototypeService(
       } catch (...) {
         std::string message("ServiceFactory threw an exception");
         registration->bundle->coreCtx->listeners.SendFrameworkEvent(
-          FrameworkEvent(FrameworkEvent::Type::FRAMEWORK_WARNING,
+          FrameworkEvent(FrameworkEvent::Type::FRAMEWORK_ERROR,
                          MakeBundle(bundle->shared_from_this()),
                          message,
-                         std::current_exception()));
+                         std::make_exception_ptr(ServiceException(message,
```
Comment (jeffdiclemente) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: Since an exception was thrown, we want to preserve the exception message and use that string as the ```message``` in the ```ServiceException``` object. Otherwise we are losing information which may be useful to users.

File: framework/src/service/ServiceReferenceBasePrivate.cpp [hunk 3]
```diff
@@ -358,10 +363,11 @@ bool ServiceReferenceBasePrivate::UngetService(
     } catch (...) {
       std::string message("ServiceFactory threw an exception");
       registration->bundle->coreCtx->listeners.SendFrameworkEvent(
-        FrameworkEvent(FrameworkEvent::Type::FRAMEWORK_WARNING,
+        FrameworkEvent(FrameworkEvent::Type::FRAMEWORK_ERROR,
                        MakeBundle(bundle->shared_from_this()),
                        message,
-                       std::current_exception()));
+                       std::make_exception_ptr(ServiceException(message,
```
Comment (jeffdiclemente) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: Since an exception was thrown, we want to preserve the exception message and use that string as the ```message``` in the ```ServiceException``` object. Otherwise we are losing information which may be useful to users.

File: framework/src/service/ServiceRegistrationBase.cpp [hunk 4]
```diff
@@ -256,10 +256,11 @@ void ServiceRegistrationBase::Unregister()
           std::string message(
             "ServiceFactory UngetService implementation threw an exception");
           d->bundle->coreCtx->listeners.SendFrameworkEvent(
-            FrameworkEvent(FrameworkEvent::Type::FRAMEWORK_WARNING,
+            FrameworkEvent(FrameworkEvent::Type::FRAMEWORK_ERROR,
                            MakeBundle(d->bundle->shared_from_this()),
                            message,
-                           std::current_exception()));
+                           std::make_exception_ptr(ServiceException(message,
```
Comment (jeffdiclemente) [inline framework/src/service/ServiceRegistrationBase.cpp]: Since an exception was thrown, we want to preserve the exception message and use that string as the ```message``` in the ```ServiceException``` object. Otherwise we are losing information which may be useful to users.

File: framework/src/service/ServiceRegistrationBase.cpp [hunk 5]
```diff
@@ -273,10 +274,11 @@ void ServiceRegistrationBase::Unregister()
         std::string message(
           "ServiceFactory UngetService implementation threw an exception");
         d->bundle->coreCtx->listeners.SendFrameworkEvent(
-          FrameworkEvent(FrameworkEvent::Type::FRAMEWORK_WARNING,
+          FrameworkEvent(FrameworkEvent::Type::FRAMEWORK_ERROR,
                          MakeBundle(d->bundle->shared_from_this()),
                          message,
-                         std::current_exception()));
+                         std::make_exception_ptr(ServiceException(message,
```
Comment (jeffdiclemente) [inline framework/src/service/ServiceRegistrationBase.cpp]: Since an exception was thrown, we want to preserve the exception message and use that string as the ```message``` in the ```ServiceException``` object. Otherwise we are losing information which may be useful to users.

File: framework/src/service/ServiceReferenceBasePrivate.cpp [hunk 6]
```diff
@@ -98,13 +100,15 @@ InterfaceMapConstPtr ServiceReferenceBasePrivate::GetServiceFromFactory(
       }
     }
     s = smap;
-  } catch (...) {
+  } catch (std::exception& ex) {
```
Comment (jeffdiclemente) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: ```std::exception&``` should be ```const```.

File: framework/src/service/ServiceReferenceBasePrivate.cpp [hunk 7]
```diff
@@ -275,13 +279,14 @@ bool ServiceReferenceBasePrivate::UngetPrototypeService(
       try {
         sf->UngetService(
           MakeBundle(bundle), ServiceRegistrationBase(registration), service);
-      } catch (...) {
+      } catch (std::exception& ex) {
```
Comment (jeffdiclemente) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: ```std::exception&``` should be ```const```.

File: framework/src/service/ServiceReferenceBasePrivate.cpp [hunk 8]
```diff
@@ -355,13 +360,14 @@ bool ServiceReferenceBasePrivate::UngetService(
     try {
       sf->UngetService(
         MakeBundle(bundle), ServiceRegistrationBase(registration), sfi);
-    } catch (...) {
+    } catch (std::exception& ex) {
```
Comment (jeffdiclemente) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: ```std::exception&``` should be ```const```.

File: framework/src/service/ServiceRegistrationBase.cpp [hunk 9]
```diff
@@ -252,14 +252,15 @@ void ServiceRegistrationBase::Unregister()
         try {
           serviceFactory->UngetService(
             MakeBundle(i.first->shared_from_this()), *this, service);
-        } catch (...) {
+        } catch (std::exception& ex) {
```
Comment (jeffdiclemente) [inline framework/src/service/ServiceRegistrationBase.cpp]: ```std::exception&``` should be ```const```.

File: framework/src/service/ServiceRegistrationBase.cpp [hunk 10]
```diff
@@ -269,14 +270,15 @@ void ServiceRegistrationBase::Unregister()
       try {
         serviceFactory->UngetService(
           MakeBundle(i.first->shared_from_this()), *this, i.second);
-      } catch (...) {
+      } catch (std::exception& ex) {
```
Comment (jeffdiclemente) [inline framework/src/service/ServiceRegistrationBase.cpp]: ```std::exception&``` should be ```const```.
