### PR TITLE
Fix #846

### LINKED ISSUE #710: listenerToken data race in ServiceTrackerPrivate
The ServiceTrackerPrivate holds a listener token. In ServiceTracker::Close(), the listener token is passed through a std::move() outside of the synchronized region for the ServiceTrackerPrivate, creating a data race when Open() and Close() calls are made concurrently.

This race is warned by TSan, but is currently suppressed.

Moving the RemoveListener call in ServiceTracker::Close() will likely resolve the race, but the possibility of re-entrancy should be examined before implementing this solution.

**To Reproduce:**
- Remove ServiceTracker lines from tsan_suppressions.txt
- Run usFrameworkTests (specifically ServiceTrackerTest.ServiceTrackerConcurrentOpenClose) in TSan

### LINKED ISSUE #846: multiple thread sanitizer issues in usFrameworkTests
These errors are from the test log: https://github.com/CppMicroServices/CppMicroServices/actions/runs/4872584091/jobs/8690974464?pr=845

These issues are reproducible by building the CppMicroServices code base with `US_ENABLE_TSAN` enabled on Linux and running usFrameworkTests repeatedly in a loop.

### PR DESCRIPTION
**Pull request by tcormackMW**
Some changes to code and suppressions for tsan as a result of a TSAN bug with waiting on condition variables

### CODE REVIEW

**Review by jeffdiclemente — CHANGES_REQUESTED** [review]
I would prefer these changes be split out into 3 separate PRs instead for easier reviews:
1. The ServiceTracker.tpp code format change (its hard to spot the functional change hidden amongst all the formatting changes).
2. Fix for #846 
3. Fix for #710

File: framework/test/bundles/libC1/TestBundleC1.cpp [hunk 1]
```diff
@@ -138,6 +132,8 @@ namespace cppmicroservices
                         count--;
                     }
                 }
+                // stop spin
```
Comment (jeffdiclemente) [inline framework/test/bundles/libC1/TestBundleC1.cpp:135]: its more helpful to other developers to example the "why" in a comment here instead of describing the "what". I recommend adding a short, succinct note about why a `sleep_for` in a loop is being used.

File: tsan_suppressions.txt [hunk 2]
```diff
@@ -2,5 +2,33 @@
 race:cppmicroservices::ServiceListeners::RemoveServiceListener
 race:cppmicroservices::ServiceTracker*
 
+# BundleRegistry races and double lock false-positives
```
Comment (jeffdiclemente) [inline tsan_suppressions.txt:5]: a link to the github issue, https://github.com/google/sanitizers/issues/1259, would be helpful here.

**Review by jeffdiclemente — CHANGES_REQUESTED** [review]

File: framework/test/bundles/libC1/TestBundleC1.cpp [hunk 3]
```diff
@@ -132,7 +136,8 @@ namespace cppmicroservices
                         count--;
                     }
                 }
-                // stop spin
+                // Rather than a condition variable, we are looping until regs is non-empty.
+                // This sleep stops the code from looping too quickly and causing slow downs.
```
Comment (jeffdiclemente) [inline framework/test/bundles/libC1/TestBundleC1.cpp:140]: Noting that we are choosing to sleep (which is more inefficient) instead of using a `condition_variable` because of a false positive coming from tsan when using `wait_for` would be useful.

**Review by jeffdiclemente — CHANGES_REQUESTED** [review]

**Review by jeffdiclemente — APPROVED** [review]
