### PR TITLE
Fix #868: Recoups some of performance losses from PR #841

### LINKED ISSUE #868: Performance regression from PR #841
Fix performance regression from above Pull Request

### PR DESCRIPTION
**Pull request by tcormackMW**
This recoups some of the performance losses from PR 841 by reducing constructor calls, removing shared_ptrs where not needed, and simplifying constructors

### CODE REVIEW

File: framework/src/service/ServiceRegistrationBase.cpp [hunk 1]
```diff
@@ -353,12 +353,9 @@ namespace cppmicroservices
...
-        ServiceReferenceBase sr1;
-        ServiceReferenceBase sr2;
-        {
-            LockServiceRegistration(), sr1 = d->reference;
-            o.LockServiceRegistration(), sr2 = o.d->reference;
-        }
+        ServiceReferenceBase sr1 = (LockServiceRegistration(), d->reference);
+        ServiceReferenceBase sr2 = (o.LockServiceRegistration(), o.d->reference);
+
         return sr1 < sr2;
```
Comment (jeffdiclemente) [inline framework/src/service/ServiceRegistrationBase.cpp:359]: the locks from `LockServiceRegistration` and `o.LockServiceRegistration` are now held while executing `operator<`. will this cause a deadlock?

Comment (jeffdiclemente) [reply framework/src/service/ServiceRegistrationBase.cpp:359]: yes, you're right. I missed that.

**Review by jeffdiclemente — APPROVED** [review]

**Review by achristoforides — APPROVED** [review]
