### PR TITLE
Reduce peak heap memory utilization. Fixes #297.

### LINKED ISSUE #297: Optimize peak heap allocation when installing bundles
When installing bundles, we are encountering prohibitive amount of peak heap allocation. This is because we call `mz_zip_reader_init_file`  with the location of the bundle deep in the call hierarchy. This miniz library call allocates and dellocates a lot of memory until it reads the zip blob to load the manifest and other resources.

The following is a sample run to illustrate the problem:
Tool : valgrind --tool=massif (heap allocation tool)
Platform : Linux
Test code: 
```cpp
    auto f = FrameworkFactory().NewFramework();
    f.Start();
    auto ctx = f.GetBundleContext();
    auto bundles = ctx.InstallBundles("testbundle.so");
```

## Massif log (parsed using ms_print)
```
99.70% (2,214,368B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->94.47% (2,098,176B) 0x61EAA30: _IO_file_doallocate (filedoalloc.c:101)
| ->94.47% (2,098,176B) 0x61F8A44: _IO_doallocbuf (genops.c:398)
|   ->94.42% (2,097,152B) 0x61F5DE1: _IO_file_seekoff@@GLIBC_2.2.5 (fileops.c:1031)
|   | ->94.42% (2,097,152B) 0x61F4287: fseeko (fseeko.c:36)
|   |   ->94.42% (2,097,152B) 0x502F7C0: mz_zip_reader_init_file (miniz.c:3377)
|   |     ->94.42% (2,097,152B) 0x4FDC25E: cppmicroservices::BundleResourceContainer::BundleResourceContainer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (BundleResourceContainer.cpp:45)
|   |       ->94.42% (2,097,152B) 0x4FE80EF: void __gnu_cxx::new_allocator<cppmicroservices::BundleResourceContainer>::construct<cppmicroservices::BundleResourceContainer, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(cppmicroservices::BundleResourceContainer*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (new_allocator.h:120)
|   |       | ->94.42% (2,097,152B) 0x4FE782C: void std::allocator_traits<std::allocator<cppmicroservices::BundleResourceContainer> >::construct<cppmicroservices::BundleResourceContainer, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::allocator<cppmicroservices::BundleResourceContainer>&, cppmicroservices::BundleResourceContainer*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (alloc_traits.h:475)
|   |       |   ->94.42% (2,097,152B) 0x4FE6CC0: std::_Sp_counted_ptr_inplace<cppmicroservices::BundleResourceContainer, std::allocator<cppmicroservices::BundleResourceContainer>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::allocator<cppmicroservices::BundleResourceContainer>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (shared_ptr_base.h:520)
|   |       |     ->94.42% (2,097,152B) 0x4FE6238: std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<cppmicroservices::BundleResourceContainer, std::allocator<cppmicroservices::BundleResourceContainer>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::_Sp_make_shared_tag, cppmicroservices::BundleResourceContainer*, std::allocator<cppmicroservices::BundleResourceContainer> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (shared_ptr_base.h:615)
|   |       |       ->94.42% (2,097,152B) 0x4FE5998: std::__shared_ptr<cppmicroservices::BundleResourceContainer, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<cppmicroservices::BundleResourceContainer>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::_Sp_make_shared_tag, std::allocator<cppmicroservices::BundleResourceContainer> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (shared_ptr_base.h:1100)
|   |       |         ->94.42% (2,097,152B) 0x4FE48DE: std::shared_ptr<cppmicroservices::BundleResourceContainer>::shared_ptr<std::allocator<cppmicroservices::BundleResourceContainer>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::_Sp_make_shared_tag, std::allocator<cppmicroservices::BundleResourceContainer> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (shared_ptr.h:319)
|   |       |           ->94.42% (2,097,152B) 0x4FE3A73: std::shared_ptr<cppmicroservices::BundleResourceContainer> std::allocate_shared<cppmicroservices::BundleResourceContainer, std::allocator<cppmicroservices::BundleResourceContainer>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::allocator<cppmicroservices::BundleResourceContainer> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (shared_ptr.h:620)
|   |       |             ->94.42% (2,097,152B) 0x4FE2E8F: std::shared_ptr<cppmicroservices::BundleResourceContainer> std::make_shared<cppmicroservices::BundleResourceContainer, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (shared_ptr.h:636)
|   |       |               ->94.42% (2,097,152B) 0x4FE22E7: cppmicroservices::BundleStorageMemory::InsertBundleLib(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (BundleStorageMemory.cpp:39)
|   |       |                 ->94.42% (2,097,152B) 0x4FCE439: cppmicroservices::BundleRegistry::Install0(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::shared_ptr<cppmicroservices::BundlePrivate>, std::allocator<std::shared_ptr<cppmicroservices::BundlePrivate> > > const&, cppmicroservices::BundlePrivate*) (BundleRegistry.cpp:106)
|   |       |                   ->94.42% (2,097,152B) 0x4FCE262: cppmicroservices::BundleRegistry::Install(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cppmicroservices::BundlePrivate*) (BundleRegistry.cpp:94)
|   |       |                     ->47.21% (1,048,576B) 0x4FF779D: cppmicroservices::CoreBundleContext::Init() (CoreBundleContext.cpp:178)
|   |       |                     | ->47.21% (1,048,576B) 0x4F08DE2: cppmicroservices::FrameworkPrivate::DoInit() (FrameworkPrivate.cpp:48)
|   |       |                     |   ->47.21% (1,048,576B) 0x4F099F9: cppmicroservices::FrameworkPrivate::Start(unsigned int) (FrameworkPrivate.cpp:190)
|   |       |                     |     ->47.21% (1,048,576B) 0x4F9E569: cppmicroservices::Bundle::Start() (Bundle.cpp:119)
|   |       |                     |       ->47.21% (1,048,576B) 0x1A51DC: BundleInstall_SimpleInstall_Test::TestBody() (BundleInstallPerformanceTest.cpp:34)
|   |       |                     |         ->47.21% (1,048,576B) 0x24CD78: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2402)
|   |       |                     |           ->47.21% (1,048,576B) 0x247B5C: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2438)
|   |       |                     |             ->47.21% (1,048,576B) 0x22DE3A: testing::Test::Run() (gtest.cc:2475)
|   |       |                     |               ->47.21% (1,048,576B) 0x22E6A6: testing::TestInfo::Run() (gtest.cc:2656)
|   |       |                     |                 ->47.21% (1,048,576B) 0x22ECCC: testing::TestCase::Run() (gtest.cc:2774)
|   |       |                     |                   ->47.21% (1,048,576B) 0x235721: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:4649)
|   |       |                     |                     ->47.21% (1,048,576B) 0x24DB51: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2402)
|   |       |                     |                       ->47.21% (1,048,576B) 0x248802: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2438)
|   |       |                     |                         
|   |       |                     ->47.21% (1,048,576B) 0x4FA5354: cppmicroservices::BundleContext::InstallBundles(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (BundleContext.cpp:495)
```

### Comments
 1. The log is to be read like a stack-trace. The functions in the bottom (indented) call the functions in the top (dedented)
 2. The bottom line is the `InstallBundles` call. We can see that for this particular bundle, it allocates ~1MB of memory for reading the metadata with 47.21% of the allocation.
 3. The other 47.21% is the allocation that happens because we try to install the embedded bundles inside the test executable(`CoreBundleContext::Init()`)
 
## Potential Optimization

This excess amount of unneeded allocation can be optimized if we can stash this zip blob into a pre-agreed, dedicated section of the shared library holding the bundle. At bundle install time, we can calculate this offset from the header of the shared library and directly seek to the location of the zip blob. 

For the ELF-format, we prototyped a solution that stashes the zip into a dedicated section of the ELF named `.us_resources` like so:

```
objcopy --add-section .us_resources=manifest.zip --set-section-flags .us_resources=noload,readonly test.so testbundle.so
```

At bundle install time, we seek to the location from the ELF headers, load the zip into memory and then use `mz_zip_reader_init_mem` to read the metadata. This significantly reduces the peak allocation as we don't use the `mz_zip_reader_init_file` call.

A run of valgrind using the prototyped solution:
```
->04.90% (61,954B) 0x4FAA0AB: cppmicroservices::BundleElfFile<cppmicroservices::Elf<2> >::GetStringTable(std::basic_ifstream<char, std::char_traits<char> >&, Elf64_Shdr*) (BundleElfFile.cpp:258)
| ->04.90% (61,954B) 0x4FA8F95: cppmicroservices::BundleElfFile<cppmicroservices::Elf<2> >::BundleElfFile(std::basic_ifstream<char, std::char_traits<char> >&, unsigned long) (BundleElfFile.cpp:135)
|   ->04.90% (61,954B) 0x4FA7848: cppmicroservices::CreateBundleElfFile(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (BundleElfFile.cpp:301)
|     ->04.90% (61,954B) 0x4FDD2E0: cppmicroservices::BundleResourceContainer::LoadZipArchive() (BundleResourceContainer.cpp:66)
|       ->04.90% (61,954B) 0x4FDD136: cppmicroservices::BundleResourceContainer::BundleResourceContainer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (BundleResourceContainer.cpp:55)
|         ->04.90% (61,954B) 0x4FE9107: void __gnu_cxx::new_allocator<cppmicroservices::BundleResourceContainer>::construct<cppmicroservices::BundleResourceContainer, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(cppmicroservices::BundleResourceContainer*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (new_allocator.h:120)
|         | ->04.90% (61,954B) 0x4FE8844: void std::allocator_traits<std::allocator<cppmicroservices::BundleResourceContainer> >::construct<cppmicroservices::BundleResourceContainer, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::allocator<cppmicroservices::BundleResourceContainer>&, cppmicroservices::BundleResourceContainer*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (alloc_traits.h:475)
|         |   ->04.90% (61,954B) 0x4FE7CD8: std::_Sp_counted_ptr_inplace<cppmicroservices::BundleResourceContainer, std::allocator<cppmicroservices::BundleResourceContainer>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::allocator<cppmicroservices::BundleResourceContainer>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (shared_ptr_base.h:520)
|         |     ->04.90% (61,954B) 0x4FE7250: std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<cppmicroservices::BundleResourceContainer, std::allocator<cppmicroservices::BundleResourceContainer>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::_Sp_make_shared_tag, cppmicroservices::BundleResourceContainer*, std::allocator<cppmicroservices::BundleResourceContainer> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (shared_ptr_base.h:615)
|         |       ->04.90% (61,954B) 0x4FE69B0: std::__shared_ptr<cppmicroservices::BundleResourceContainer, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<cppmicroservices::BundleResourceContainer>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::_Sp_make_shared_tag, std::allocator<cppmicroservices::BundleResourceContainer> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (shared_ptr_base.h:1100)
|         |         ->04.90% (61,954B) 0x4FE58F6: std::shared_ptr<cppmicroservices::BundleResourceContainer>::shared_ptr<std::allocator<cppmicroservices::BundleResourceContainer>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::_Sp_make_shared_tag, std::allocator<cppmicroservices::BundleResourceContainer> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (shared_ptr.h:319)
|         |           ->04.90% (61,954B) 0x4FE4A8B: std::shared_ptr<cppmicroservices::BundleResourceContainer> std::allocate_shared<cppmicroservices::BundleResourceContainer, std::allocator<cppmicroservices::BundleResourceContainer>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::allocator<cppmicroservices::BundleResourceContainer> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (shared_ptr.h:620)
|         |             ->04.90% (61,954B) 0x4FE3EA7: std::shared_ptr<cppmicroservices::BundleResourceContainer> std::make_shared<cppmicroservices::BundleResourceContainer, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (shared_ptr.h:636)
|         |               ->04.90% (61,954B) 0x4FE32FF: cppmicroservices::BundleStorageMemory::InsertBundleLib(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (BundleStorageMemory.cpp:39)
|         |                 ->04.90% (61,954B) 0x4FCF357: cppmicroservices::BundleRegistry::Install0(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::shared_ptr<cppmicroservices::BundlePrivate>, std::allocator<std::shared_ptr<cppmicroservices::BundlePrivate> > > const&, cppmicroservices::BundlePrivate*) (BundleRegistry.cpp:106)
|         |                   ->04.90% (61,954B) 0x4FCF180: cppmicroservices::BundleRegistry::Install(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cppmicroservices::BundlePrivate*) (BundleRegistry.cpp:94)
|         |                     ->04.90% (61,954B) 0x4FA5874: cppmicroservices::BundleContext::InstallBundles(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (BundleContext.cpp:495)
```

### Comments
 1. We use only 61KB of peak allocation with the new solution. For this particular case, 4.9% of peak allocation.
 
## Proposal

 1. Propose dedicated sections in the executables in each platform to hold the metadata. For e.g. `.us_resources`
   * For ELF, we currently store the embedded metadata in .rodata. I think stashing the zip in a custom section will be even better than using a section pre-defined in the ELF format.
 2. Change the framework code to read directly from the sections we agreed upon in 1. This will be platform-specific.
   * If there's any failure, fall back to the costlier `mz_zip_reader_init_file` route.
   
 This will be of significant help to clients who load lots of bundles as a part of application startup or any other time.

### PR DESCRIPTION
**Pull request by jeffdiclemente**
This is a re-factoring of the BundleObj* classes which includes the ability to read the data section where the bundle's zip file is embedded using the link option.

I removed one aspect of the original BundleObj* classes, which was to get the bundle name. I feel that this information is retrievable already and since there no clear use case for it, I've removed it for now.

While not allowed right now, this code can be modified to allow reading of different file formats on different host machines. For example; reading PE files on macOS or reading ELF files on Windows. I chose not to enable this capability yet since the focus is on reducing heap utilization.

### CODE REVIEW

File: util/include/cppmicroservices/util/BundleElfFile.h [hunk 1]
```diff
@@ -222,21 +228,33 @@ class BundleElfFile
...
+      return nullptr;
+    }
 
     fs.seekg(strTblHdr->sh_offset);
-    char* strTbl = new char[static_cast<std::size_t>(strTblHdr->sh_size)];
-    fs.read(strTbl, strTblHdr->sh_size);
-    m_StrTblIndexToStrArray.insert(std::make_pair(strTblHdrIdx, strTbl));
+    char* strTbl = nullptr;
+    try {
+        strTbl = new char[static_cast<std::size_t>(strTblHdr->sh_size)];
```
Comment (karthikreddy09) [inline util/include/cppmicroservices/util/BundleElfFile.h]: probably unrelated to this change but this whole file looks like a mix of old and new programming styles. 
explicit new/delete calls, malloc/free calls, functions returning C-style strings etc. Could be refactored to be more expressive and readable.

File: util/include/cppmicroservices/util/BundleMachOFile.h [hunk 2]
```diff
@@ -71,6 +72,35 @@ I readBE(I i)
...
+  fs.read(reinterpret_cast<char*>(&segment), sizeof(SegmentCommand));
+  if(0 == strcmp("__TEXT", segment.segname)) {
+    // find "us_resources" section
+    for (uint32_t i = 0; i < segment.nsects; ++i) {
+      Section section;
+      fs.read(reinterpret_cast<char*>(&section), sizeof(Section));
+      if (0 == strcmp("us_resources", section.sectname)) {
+        uint64_t zipSize = section.size;
+        if (0 < zipSize) {
+          void* zipData = malloc(zipSize * sizeof(char));
```
Comment (karthikreddy09) [inline util/include/cppmicroservices/util/BundleMachOFile.h]:
```suggestion
          std::unique_ptr<char[]> zipData = std::unique_ptr(new char[zipSize]);
          if(zipData) {
            fs.seekg(fileOffset + section.offset);
            fs.read(zipData.get(), zipSize);
            return std::make_shared<RawBundleResources>( std::move(zipData), zipSize );
          }
```

File: util/include/cppmicroservices/util/BundleObjFile.h [hunk 3]
```diff
@@ -40,18 +42,39 @@ struct InvalidObjFileException : public std::exception
   std::string m_What;
 };
 
+// Represents the raw bundle resource data.
+// The data buffer is the bits representing a zip file.
+// The data size is the zip file's size in bytes.
+struct RawBundleResources
+{
+  RawBundleResources(std::unique_ptr<void, void(*)(void*)> data, uint64_t dataSize)
```
Comment (karthikreddy09) [inline util/include/cppmicroservices/util/BundleObjFile.h]: All call sites seem to have a pattern of 
1. allocate a buffer
2. read data into buffer from stream
3. transfer ownership of the buffer to RawBundleResources object

I think you can encapsulate the memory allocation/release inside this class and avoid the repetitive steps at call sites.

example usage ...

```
std::unique_ptr<RawBundleResources> zipData = new RawBundleResources(zipSize);
if(zipData) {
  fs.seekg(fileOffset + section.offset);
  fs.read(zipData.get<char>(), zipSize);
  return zipData;
}
```
instead of 

```
std::unique_ptr<char[]> zipData = std::unique_ptr(new char[zipSize]);
  if(zipData) {
   fs.seekg(fileOffset + section.offset);
   fs.read(zipData.get(), zipSize);
   return std::make_shared<RawBundleResources>( std::move(zipData), zipSize );
 }
```

File: util/include/cppmicroservices/util/BundleObjFile.h [hunk 4]
```diff
@@ -40,18 +42,39 @@ struct InvalidObjFileException : public std::exception
...
+  : m_Data(std::move(data))
+  , m_DataSize(dataSize)
+  { }
+
+  operator bool() const
+  {
+    return m_Data && m_DataSize > 0;
```
Comment (karthikreddy09) [inline util/include/cppmicroservices/util/BundleObjFile.h]:
```suggestion
    return m_Data && (m_DataSize > 0);
```

File: util/include/cppmicroservices/util/BundleElfFile.h [hunk 5]
```diff
@@ -222,21 +228,33 @@ class BundleElfFile
...
+        fs.read(strTbl, strTblHdr->sh_size);
+        m_StrTblIndexToStrArray.insert(std::make_pair(strTblHdrIdx, strTbl));
+    } catch (...) {
+      if (strTbl) {
+        delete[] strTbl;
```
Comment (ksubramz) [inline util/include/cppmicroservices/util/BundleElfFile.h]: You can get rid of `try..catch..` if `strTbl` is a unique_ptr to the new array? And return the unique_ptr from the function and make corresponding adjustments at the call-site (looks like there is only one)

File: framework/src/bundle/BundleResourceContainer.cpp [hunk 6]
```diff
@@ -37,15 +40,27 @@ namespace cppmicroservices {
...
+  // Assume that the bundle had its meta-data linked into a data section.
+  // If this assumption is false, fall back to reading the meta-data in a
+  // less than optimal way, in terms of memory utilization.
+  try {
+    auto objFile = BundleObjFactory().CreateBundleFileObj(location);
+    m_Data = objFile->GetRawBundleResourceContainer();
+  } catch(...) {}
+
+  if (!m_Data ||
+      !mz_zip_reader_init_mem(&m_ZipArchive, m_Data->m_Data.get(), m_Data->m_DataSize, 0)) {
```
Comment (ksubramz) [inline framework/src/bundle/BundleResourceContainer.cpp]: `m_Data->m_Data` looks odd. Maybe `BundleResourceContainer`'s member can be something like `m_RawBundleResource`, so that this can be `m_RawBundleResource->m_Data`

File: framework/test/gtest/BundleObjFileTest.cpp [hunk 7]
```diff
@@ -0,0 +1,100 @@
...
+#endif
+  ASSERT_NO_THROW({
+    auto bundleObj = cppmicroservices::BundleObjFactory().CreateBundleFileObj(testBundleRLPath);
+    auto libName = bundleObj->GetLibraryName();
+    ASSERT_STREQ(libName.c_str(), goldLibName.c_str());
+  });
+}
+
+
+TEST(BundleObjFile, GetRawBundleResourceContainer)
```
Comment (ksubramz) [inline framework/test/gtest/BundleObjFileTest.cpp]: Nice to have a test point for each platform that gets the `rawBundleResource` for a valid bundle and then can successfully do a `mz_zip_reader_init_mem` on the `m_Data`.

This can be also done in a later commit.

File: util/include/cppmicroservices/util/BundleElfFile.h [hunk 8]
```diff
@@ -144,62 +145,67 @@ class BundleElfFile
...
            iterEnd = m_StrTblIndexToStrArray.end();
          iter != iterEnd;
          ++iter) {
       delete[] iter->second;
     }
-
-    delete[] m_SectionHeaders;
   }
 
   virtual std::vector<std::string> GetDependencies() const { return m_Needed; }
```
Comment (ksubramz) [inline util/include/cppmicroservices/util/BundleElfFile.h]: Omit `virtual` and add `override`?

(this comment for all instances of where such a change applies)

File: util/include/cppmicroservices/util/BundleMachOFile.h [hunk 9]
```diff
@@ -160,24 +154,14 @@ class BundleMachOFile
 
   virtual std::vector<std::string> GetDependencies() const { return m_Needed; }
```
Comment (ksubramz) [inline util/include/cppmicroservices/util/BundleMachOFile.h]: same - omit `virtual` and add `override`

File: util/include/cppmicroservices/util/BundlePEFile.h [hunk 10]
```diff
@@ -26,124 +26,138 @@
...
+          fs.read(reinterpret_cast<char*>(&importDesc), sizeof importDesc);
+          ++currDirEntry;
+        }
       }
     }
-
-    delete[] m_SectionHeaders;
   }
 
   virtual std::vector<std::string> GetDependencies() const { return m_Needed; }
```
Comment (ksubramz) [inline util/include/cppmicroservices/util/BundlePEFile.h]: same - omit `virtual` and add `override`

File: util/include/cppmicroservices/util/BundleElfFile.h (hunk 1 above)
Comment (jeffdiclemente) [reply util/include/cppmicroservices/util/BundleElfFile.h]: I tried using a ```std::string``` instead of a ```char*``` in ```m_StrTblIndexToStrArray```, the problem is that the calling code doesn't want a string, it wants a pointer. I can try to make the ```char*``` a ```std::unique_ptr<char[]>``` instead.

File: util/include/cppmicroservices/util/BundleElfFile.h (hunk 5 above)
Comment (jeffdiclemente) [reply util/include/cppmicroservices/util/BundleElfFile.h]: I can't do that since ```m_StrTblIndexToStrArray``` owns ```strTbl```.  Since there is only one call to ```GetStringTable```, I can do away with ```m_StrTblIndexToStrArray``` altogether and return ```std::unique_ptr<char[]>```. There isn't a need to cache the string table right now anyway (which I believe was the point of ```m_StrTblIndexToStrArray```).

File: util/include/cppmicroservices/util/BundleMachOFile.h (hunk 2 above)
Comment (jeffdiclemente) [reply util/include/cppmicroservices/util/BundleMachOFile.h]: The miniz api, ```mz_zip_reader_init_mem``` takes a ```void*``` for the data. I chose to use ```malloc```/```free``` so I wouldn't have to to use casts.

File: util/include/cppmicroservices/util/BundlePEFile.h [hunk 11]
```diff
@@ -20,130 +20,142 @@
...
-
-  virtual std::string GetLibName() const { return m_Soname; }
+  std::vector<std::string> GetDependencies() const override { return m_Needed; }
 
-  virtual std::string GetBundleName() const { return m_BundleName; }
+  std::string GetLibraryName() const override { return m_Soname; }
+    
+  std::shared_ptr<RawBundleResources> GetRawBundleResourceContainer() const override
+  {
+    HMODULE hBundleResources = LoadLibraryEx(m_Location.c_str(), nullptr, LOAD_LIBRARY_AS_DATAFILE | LOAD_LIBRARY_AS_IMAGE_RESOURCE);
```
Comment (saschazelzer) [inline util/include/cppmicroservices/util/BundlePEFile.h]: Should we not check for errors when calling all the Windows API functions?

File: util/include/cppmicroservices/util/MappedFile.h [hunk 12]
```diff
@@ -0,0 +1,77 @@
...
+    , mappedAddress(nullptr)
+    , mapSize(0) {}
+  MappedFile(const std::string& fileLocation, size_t mapLength, off_t offset)
+    : fileDesc(-1)
+    , mappedAddress(nullptr)
+    , mapSize(mapLength)
+  {
+    fileDesc = open(fileLocation.c_str(), O_RDONLY);
+    if(fileDesc >= 0) {
+      mappedAddress = mmap(0, mapLength, PROT_READ, MAP_PRIVATE, fileDesc, offset);
```
[the remark this answers is not in the document]
Comment (jeffdiclemente) [reply util/include/cppmicroservices/util/MappedFile.h]: good catch. mmap will return -1 (MAP_FAILED) on error, that will most likely get converted to some bogus memory address. I'll fix it.

**Comment by jeffdiclemente** [comment]
@saschazelzer can you take a look? If possible, I'd like to merge by tomorrow Nov 14th. 
I looked at the memory usage using a bundle with larger resources (3MB compressed) and the memory footprint is comparable between using memory map and using miniz to read the zip contents from the bundle.

File: util/include/cppmicroservices/util/BundlePEFile.h (hunk 11 above)
Comment (saschazelzer) [reply util/include/cppmicroservices/util/BundlePEFile.h]: Good to know, thanks.

File: framework/src/bundle/BundleResourceContainer.cpp [hunk 13]
```diff
@@ -179,6 +181,27 @@ void BundleResourceContainer::FindNodes(
...
+{
+  // Assume that the bundle had its meta-data linked into a data section.
+  // If this assumption is false, fall back to reading the meta-data in a
+  // less than optimal way, in terms of memory utilization.
+  std::shared_ptr<RawBundleResources> rawBundleResourceData;
+  try {
+    m_ObjFile = BundleObjFactory().CreateBundleFileObj(m_Location);
+    rawBundleResourceData = m_ObjFile->GetRawBundleResourceContainer();
+  }
+  catch (const std::exception&) {}
```
Comment (saschazelzer) [inline framework/src/bundle/BundleResourceContainer.cpp]: Does it make sense to log exceptions here, or just let it propagate upward, as we do with zip init errors below?

Comment (jeffdiclemente) [reply framework/src/bundle/BundleResourceContainer.cpp]: I don't want to propagate the exception since I do want to attempt to load the zip file using ```mz_zip_reader_init_file``` as a fallback strategy.

logging the exception using the internal logger makes sense. I'll do that.

**Comment by jeffdiclemente** [comment]
@CppMicroServices/developers I'll merge this into development on Monday, Nov 19th unless there are more issues to resolve.
