### PR TITLE
Fix for ServiceReferenceBasePrivate race condition

### LINKED ISSUE #202: A race condition in ServiceReferenceBasePrivate causes a seg fault
A race can occur when a client retrieves a service from a ```ServiceFactory``` using ```BundleContext::GetService(ref)```. The race leads to a seg fault which occurs as a result of trying to access a ```nullptr``` service object returned from an empty ```std::unordered_map``` of cached service objects, maintained by CppMicroServices.

The following function, when added to and called in ```framework/test/ServiceFactoryTest.cpp```, will reproduce the issue on Linux and Mac. The issue doesn't reproduce on Windows.

```
#ifdef US_ENABLE_THREADING_SUPPORT

// test that concurrent calls to ServiceFactory::GetService and ServiceFactory::UngetService
// don't cause race conditions.
void TestConcurrentServiceFactory()
{
  auto framework = FrameworkFactory().NewFramework();
  framework.Start();

  auto bundle = testing::InstallLib(framework.GetBundleContext(), "TestBundleH");
  bundle.Start();

  std::vector<std::thread> worker_threads;
  for (size_t i = 0; i < 100; ++i)
  {
    worker_threads.push_back(std::thread([framework]()
        {
          for (int i = 0; i < 1000; ++i)
          {
              auto frameworkCtx = framework.GetBundleContext();
              if (frameworkCtx)
              {
                auto ref = frameworkCtx.GetServiceReference<cppmicroservices::TestBundleH>();
                if (ref)
                {
                  std::shared_ptr<cppmicroservices::TestBundleH> svc = frameworkCtx.GetService(ref);
                  US_TEST_CONDITION_REQUIRED(svc, "test for valid service object");
                }
              }
          }
        }));
  }

  for (auto& t : worker_threads) t.join();
}
#endif
```

The stack trace from the resulting seg fault is

```
0x00000000005d5929 in std::_Rb_tree<std::string, std::pair<std::string const, std::shared_ptr<void> >, std::_Select1st<std::pair<std::string const, std::shared_ptr<void> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::shared_ptr<void> > > >::_M_begin (this=0x0) at gcc-4.9.3/include/c++/4.9.3/bits/stl_tree.h:524
524		  (this->_M_impl._M_header._M_parent);
(gdb) bt
#0  0x00000000005d5929 in std::_Rb_tree<std::string, std::pair<std::string const, std::shared_ptr<void> >, std::_Select1st<std::pair<std::string const, std::shared_ptr<void> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::shared_ptr<void> > > >::_M_begin (this=0x0) at gcc-4.9.3/include/c++/4.9.3/bits/stl_tree.h:524
#1  0x00000000005d4a57 in std::_Rb_tree<std::string, std::pair<std::string const, std::shared_ptr<void> >, std::_Select1st<std::pair<std::string const, std::shared_ptr<void> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::shared_ptr<void> > > >::find (this=0x0, __k=...) at gcc-4.9.3/include/c++/4.9.3/bits/stl_tree.h:1926
#2  0x00000000005d3a60 in std::map<std::string, std::shared_ptr<void>, std::less<std::string>, std::allocator<std::pair<std::string const, std::shared_ptr<void> > > >::find (this=0x0, __x=...)
    at gcc-4.9.3/include/c++/4.9.3/bits/stl_map.h:875
#3  0x00007ffff769d6ae in cppmicroservices::ExtractInterface (map=..., interfaceId=...)
    at CppMicroServices/framework/include/cppmicroservices/ServiceInterface.h:325
#4  0x00007ffff769bf81 in cppmicroservices::ServiceReferenceBasePrivate::GetService (this=0x7fffe4000970, bundle=0x931a80)
    at CppMicroServices/framework/src/service/ServiceReferenceBasePrivate.cpp:106
#5  0x00007ffff76c5151 in cppmicroservices::BundleContext::GetService (this=0x7fffdfffee10, reference=...)
    at CppMicroServices/framework/src/bundle/BundleContext.cpp:282
#6  0x00000000005d4958 in cppmicroservices::BundleContext::GetService<cppmicroservices::TestBundleH> (this=0x7fffdfffee10, reference=...)
    at CppMicroServices/framework/include/cppmicroservices/BundleContext.h:581
#7  0x00000000005d0f25 in <lambda()>::operator()(void) const (__closure=0x935708) at ./CppMicroServices/framework/test/ServiceFactoryTest.cpp:198
#8  0x00000000005d3656 in std::_Bind_simple<TestConcurrentServiceFactory()::<lambda()>()>::_M_invoke<>(std::_Index_tuple<>) (this=0x935708)
    at gcc-4.9.3/include/c++/4.9.3/functional:1700
#9  0x00000000005d34be in std::_Bind_simple<TestConcurrentServiceFactory()::<lambda()>()>::operator()(void) (this=0x935708)
    at gcc-4.9.3/include/c++/4.9.3/functional:1688
#10 0x00000000005d33ad in std::thread::_Impl<std::_Bind_simple<TestConcurrentServiceFactory()::<lambda()>()> >::_M_run(void) (this=0x9356f0)
    at gcc-4.9.3/include/c++/4.9.3/thread:115
#11 0x00007ffff70d4970 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#12 0x00007ffff68f2064 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#13 0x00007ffff662762d in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

### PR DESCRIPTION
**Pull request by jeffdiclemente**
Fixes #202 

This fixes a race condition involving how ServiceReferenceBasePrivate tracks the cached service instance and the list of dependent bundles.

### CODE REVIEW

File: framework/src/service/ServiceReferenceBasePrivate.cpp [hunk 1]
```diff
@@ -106,7 +117,7 @@ std::shared_ptr<void> ServiceReferenceBasePrivate::GetService(BundlePrivate* bun
   auto s = ExtractInterface(GetServiceInterfaceMap(bundle), interfaceId);
   if (!s)
   {
-    registration->Lock(), --registration->dependents[bundle];
+    registration->Lock(), --registration->dependents.at(bundle);
```
Comment (saschazelzer) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: If `GetServiceInterfaceMap` above returned early, the `.at(bundle)` might throw now, which would propagate into client code. I think it would be better to `find` the bundle.

Also (this problem is not new), if `GetServiceInterfaceMap` returns before incrementing the count, we might decrement it "too much".

File: framework/src/service/ServiceReferenceBasePrivate.cpp [hunk 2]
```diff
@@ -115,52 +126,42 @@ InterfaceMapConstPtr ServiceReferenceBasePrivate::GetServiceInterfaceMap(BundleP
 {
   InterfaceMapConstPtr s;
   if (!registration->available) return s;
-
   std::shared_ptr<ServiceFactory> serviceFactory;
-  int count = 0;
 
+  auto l = registration->Lock(); US_UNUSED(l);
```
Comment (saschazelzer) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: Now this lock is held while calling into client code (the service factoy), which must be avoided. The original code avoided that, but had that race condition you found.

File: framework/src/service/ServiceReferenceBasePrivate.cpp [hunk 3]
```diff
@@ -115,52 +126,42 @@ InterfaceMapConstPtr ServiceReferenceBasePrivate::GetServiceInterfaceMap(BundleP
...
 
   if (!serviceFactory)
   {
-    auto l = registration->Lock(); US_UNUSED(l);
-          s = registration->service;
-    if (s && !s->empty()) ++registration->dependents[bundle];
+    s = registration->service;
+    if (s && !s->empty())
+    {
+      ++registration->dependents.at(bundle);
```
Comment (saschazelzer) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: Why the `.at`? If the bundle is not know to the map, we should insert it, using`[]`.

File: framework/src/service/ServiceReferenceBasePrivate.cpp [hunk 4]
```diff
@@ -115,52 +126,42 @@ InterfaceMapConstPtr ServiceReferenceBasePrivate::GetServiceInterfaceMap(BundleP
...
+    }
+    return s;
+  }
+
+  if (0 == registration->dependents.at(bundle))
```
Comment (saschazelzer) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: The `.at` could throw again. `[]` is find in my opinion (having a bundle entry with default `0` count is fine).

File: framework/src/service/ServiceReferenceBasePrivate.cpp [hunk 5]
```diff
@@ -115,52 +126,42 @@ InterfaceMapConstPtr ServiceReferenceBasePrivate::GetServiceInterfaceMap(BundleP
...
+  {
+    // No cached service instance exists. Get a new one and cache it.
+    s = GetServiceFromFactory(bundle, serviceFactory);
+    registration->bundleServiceInstance.insert(std::make_pair(bundle, s));
+    if (s && !s->empty()) ++registration->dependents.at(bundle);
```
Comment (saschazelzer) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: Same `.at` question here.

File: framework/test/bundles/libH/TestBundleH.cpp [hunk 6]
```diff
@@ -66,19 +67,20 @@ class TestProduct2 : public TestProduct, public TestBundleH2
 class TestBundleHPrototypeServiceFactory : public PrototypeServiceFactory
```
Comment (saschazelzer) [inline framework/test/bundles/libH/TestBundleH.cpp]: The service factory implementation could call back into the framework (by e.g. getting another service). This would test if you get a deadlock, which should happen with the proposed changes.

File: framework/src/service/ServiceReferenceBasePrivate.cpp (hunk 1 above)
Comment (jeffdiclemente) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: I'm missing something. I don't see a case where ```GetServiceInterfaceMap``` could return a valid ```InterfaceMapConstPtr``` object without ensuring that ```registration->dependents``` has a valid element in it with an incremented count.

File: framework/src/service/ServiceReferenceBasePrivate.cpp (hunk 3 above)
Comment (jeffdiclemente) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: The insertion happens on lines 136-139.

File: framework/src/service/ServiceReferenceBasePrivate.cpp (hunk 2 above)
Comment (jeffdiclemente) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: I agree, we shouldn't hold locks while calling client code. In this case, I think the only way a deadlock occurs is if the client's ```ServiceFactory::GetService``` implementation calls ```GetServiceReference/GetService``` on itself since the lock is on the ```ServiceRegistrationBasePrivate``` object associated with the ```ServiceFactory``` object. I'm sure a deadlock could occur, I don't know how likely that is to happen.

An alternative solution is to scope the locks such that ```GetServiceFromFactory(...)``` is unconditionally called and the return value is discarded if a cached service object already exists. This seems wasteful.

These are the only two options I could come up with that fixed the race condition. What are your thoughts?

File: framework/src/service/ServiceReferenceBasePrivate.cpp (hunk 4 above)
Comment (jeffdiclemente) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: read/writes to ```registration->dependents``` are guarded in ```ServiceReferenceBasePrivate::GetServiceInterfaceMap``` and ```ServiceReferenceBasePrivate::UngetService```. At this point in the code ```.at()``` should be guaranteed to find an element. Did I miss a spot where ```registration->dependents``` is not guarded?

File: framework/test/bundles/libH/TestBundleH.cpp (hunk 6 above)
Comment (jeffdiclemente) [inline framework/test/bundles/libH/TestBundleH.cpp]: excellent idea. I'm going to take a little time to do this and see if I can break the framework.

File: framework/src/service/ServiceReferenceBasePrivate.cpp (hunk 1 above)
Comment (saschazelzer) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: For a valid `InterfaceMapConstPtr` the code looks fine, but I am concerned about the invalid case.

First, if `GetServiceInterfaceMap` returns a `null` map (in case `registration->available` if `false` or due to some other condition (e.g. the race you found), then `ExtractInterface` will dereference an nullptr (we should fix that).

Second, in the invalid case, the counter was not incremented in `GetServiceInterfaceMap` (I believe) but we decrement it here. The decrement is necessary if `GetServiceInterfaceMap` returns a valid map (and hence incremented the counter) but `ExtractInterface` fails (because e.g. `interfaceId` is empty. We currently do not differentiate the two cases.

File: framework/src/service/ServiceReferenceBasePrivate.cpp (hunk 2 above)
Comment (saschazelzer) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: I agree, something needs to call `GetService` on the same service registration. But since a service factory can call into arbitrary framework API, e.g. starting bundles, which then can again do arbitrary things in their activator etc., I think we should make that bullet proof.

Discarding a second instance was the strategy used before. This is an exceptional case and not likely to occur. I would favor no deadlocks instead of optimizing service creation for corner cases :)

To avoid the race you found, would it be enough to check (in the first registration lock scope) if we have a service factory and the usage count is > 0, then return the cached instance? If not, go out of scope and execute the original code.

File: framework/src/service/ServiceReferenceBasePrivate.cpp (hunk 3 above)
Comment (saschazelzer) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: Ah, you are right. But then we can't we just use `[]` instead?

File: framework/src/service/ServiceReferenceBasePrivate.cpp (hunk 4 above)
Comment (saschazelzer) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: If think you are right. I would still prefer the usage of `[]` in that area. If existence is guaranteed anyway, we can avoid the bounds checking done in `.at`. Even if it is not guaranteed, creating an entry does not do harm and we do not need to reason about existence and possible `out_of_range` exceptions.

File: framework/src/service/ServiceReferenceBasePrivate.cpp (hunk 1 above)
Comment (jeffdiclemente) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: Understood. I'll fix the logic.

File: framework/src/service/ServiceReferenceBasePrivate.cpp (hunk 2 above)
Comment (jeffdiclemente) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: Agreed on removing the deadlock. I prematurely optimized for service creation.

I'm not sure if that will be sufficient to eliminate the race condition. I will take a closer look. 
In general, since ```ServiceReferenceBasePrivate::GetServiceInterfaceMap``` and ```ServiceReferenceBasePrivate::UngetService``` both modify the ```registration->dependents``` and ```registration->bundleServiceInstance``` data structures concurrently, all access (i.e. read and write) must be done within locks to guarantee no race conditions.

File: framework/src/service/ServiceReferenceBasePrivate.cpp (hunk 4 above)
Comment (jeffdiclemente) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: Thanks for the suggestion, I've used it to simplify this logic. I will have an update to this PR shortly.

I prefer using ```at()``` over ```operator[]``` since I feel it makes the code easier to maintain. While all uses of ```at()``` are guaranteed not to throw, an exception being thrown would indicate a bug in the logic. If ```operator[]``` is used a potential bug of this kind would be harder to see.

**Comment by jeffdiclemente** [comment]
FYI, failures are from travis CI timing out on memcheck_ServiceFactoryTest

File: framework/src/service/ServiceReferenceBasePrivate.cpp [hunk 7]
```diff
@@ -103,64 +114,51 @@ InterfaceMapConstPtr ServiceReferenceBasePrivate::GetPrototypeService(const Bund
 
 std::shared_ptr<void> ServiceReferenceBasePrivate::GetService(BundlePrivate* bundle)
 {
-  auto s = ExtractInterface(GetServiceInterfaceMap(bundle), interfaceId);
-  if (!s)
-  {
-    registration->Lock(), --registration->dependents[bundle];
-  }
-  return s;
+  return ExtractInterface(GetServiceInterfaceMap(bundle), interfaceId);
```
Comment (saschazelzer) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: The impl of `ExtractInterface` should still be improved. When it gets a null shared_ptr, it will dereference it. I think this is were the code originally crashed due to the race in `GetServiceInterfaceMap`.

File: framework/src/service/ServiceReferenceBasePrivate.cpp [hunk 8]
```diff
@@ -103,64 +114,51 @@ InterfaceMapConstPtr ServiceReferenceBasePrivate::GetPrototypeService(const Bund
...
 }
 
 InterfaceMapConstPtr ServiceReferenceBasePrivate::GetServiceInterfaceMap(BundlePrivate* bundle)
 {
   InterfaceMapConstPtr s;
   if (!registration->available) return s;
-
   std::shared_ptr<ServiceFactory> serviceFactory;
-  int count = 0;
```
Comment (saschazelzer) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: I think we should keep that variable, see comment below.

File: framework/src/service/ServiceReferenceBasePrivate.cpp [hunk 9]
```diff
@@ -103,64 +114,51 @@ InterfaceMapConstPtr ServiceReferenceBasePrivate::GetPrototypeService(const Bund
...
+      return s;
     }
   }
+
+  // Calling into a service factory could cause re-entrancy into the
+  // framework and even, theoretically, into this function. Ensuring
+  // we don't hold a lock while calling into the service factory eliminates
+  // the possibility of a deadlock. It does not however eliminate the
+  // possbilituy of infinite recursion.
+  s = GetServiceFromFactory(bundle, serviceFactory);
```
Comment (saschazelzer) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: At this point, we are unlocked and know, that we have a service factory. Previously, we would try to reuse a previously cached service instance but we were missing a check for the race condition. I think we can still avoid calling `GetServiceFromFactory` every time and reuse the cached version while checking a possible race:

Case 1 `count < 1`: This case was handled fine in the original code. We call `GetServiceFromFactory`, then lock and check the count again. If it is still < 1 we insert the new instance into our cache (the map) and are done. If It is >= 1 now, we discard the newly created instance and return the (recently added) instance from the cache.

Case 2 `count >= 1`: Lock and get the cached instance. Now (this was missing originally) if the instance is `null` (because of the race) we need to go back to case 1 (probably do case 1 and 2 in a `while(!s)` loop. If it is not `null`, we increase the count and return.

Did I miss something?

File: framework/test/bundles/libH/TestBundleH.cpp [hunk 10]
```diff
@@ -88,30 +101,106 @@ class TestBundleHPrototypeServiceFactory : public PrototypeServiceFactory
 class TestBundleHServiceFactory : public ServiceFactory
 {
   std::map<long, std::shared_ptr<TestProduct>> fcbind;   // Map calling bundle with implementation
+  std::mutex fcbindLock;
 public:
 
   InterfaceMapConstPtr GetService(const Bundle& caller, const ServiceRegistrationBase& /*sReg*/)
   {
-    std::cout << "GetService in H" << std::endl;
+    // This code causes infinite recursion into this function. It can be used as a test case
```
Comment (saschazelzer) [inline framework/test/bundles/libH/TestBundleH.cpp]: Nice. I will enable this when working on #213 .

File: framework/src/service/ServiceReferenceBasePrivate.cpp (hunk 7 above)
Comment (jeffdiclemente) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: good catch. The code changes should guarantee that ```nullptr``` is never passed to ```ExtractInterface``` (in all failure modes, it should be a default constructed ```InterfaceMapConstPtr```). Nevertheless its a good idea to ensure it never can dereference a ```nullptr```. I'll fix it.

File: framework/src/service/ServiceReferenceBasePrivate.cpp (hunk 9 above)
Comment (jeffdiclemente) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: My goal was to simplify the code and reduce the number of conditional branches (at the cost of multiple ```GetServiceFromFactory``` calls).
 
It is possible to avoid calling ```GetServiceFromFactory``` each time and still have no race condition. The drawback is that duplicate code would be required in both locked regions of code. 
Once the code exits the first lock, no assumptions can be made about the state of ```registration->dependents``` and ```registration->bundleServiceInstance``` when entering the second lock. Both locked regions of code need to do similar, if not the same, checks after acquiring the lock.

Is this drawback (i.e. duplicate code) acceptable?

**Comment by saschazelzer** [comment]
In my opinion, yes. We are only talking about a few lines of code here. But service creation via a factory can be arbitrarily costly, because it is not under our control.

On June 23, 2017 4:37:27 PM GMT+02:00, Jeff DiClemente <notifications@github.com> wrote:
>jeffdiclemente commented on this pull request.
>
>
>
>>      }
>   }
>+
>+  // Calling into a service factory could cause re-entrancy into the
>+  // framework and even, theoretically, into this function. Ensuring
>+  // we don't hold a lock while calling into the service factory
>eliminates
>+  // the possibility of a deadlock. It does not however eliminate the
>+  // possbilituy of infinite recursion.
>+  s = GetServiceFromFactory(bundle, serviceFactory);
>
>My goal was to simplify the code and reduce the number of conditional
>branches (at the cost of multiple ```GetServiceFromFactory``` calls).
> 
>It is possible to avoid calling ```GetServiceFromFactory``` each time
>and still have no race condition. The drawback is that duplicate code
>would be required in both locked regions of code. 
>Once the code exits the first lock, no assumptions can be made about
>the state of ```registration->dependents``` and
>```registration->bundleServiceInstance``` when entering the second
>lock. Both locked regions of code need to do similar, if not the same,
>checks after acquiring the lock.
>
>Is this drawback (i.e. duplicate code) acceptable?
>
>-- 
>You are receiving this because your review was requested.
>Reply to this email directly or view it on GitHub:
>https://github.com/CppMicroServices/CppMicroServices/pull/214#discussion_r123763118

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jeffdiclemente** [comment]
Ok. I will make that change

File: framework/src/service/ServiceReferenceBasePrivate.cpp [hunk 11]
```diff
@@ -103,64 +114,58 @@ InterfaceMapConstPtr ServiceReferenceBasePrivate::GetPrototypeService(const Bund
...
+
+  auto l = registration->Lock(); US_UNUSED(l);
+
+  registration->dependents.insert(std::make_pair(bundle, 0));
+
+  if (s && !s->empty())
```
Comment (saschazelzer) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: There is a really strange but possible scenario: What if the call to the service factory above returned a null service object, but another thread created a valid instance a micro second earlier and the framework cached it. Then we would return a null service even though we have a non-null cached instance. I think we should check for an existing cached service instance in an else branch and then return it if available.

File: framework/src/service/ServiceReferenceBasePrivate.cpp [hunk 12]
```diff
@@ -103,64 +114,58 @@ InterfaceMapConstPtr ServiceReferenceBasePrivate::GetPrototypeService(const Bund
...
+  {
+    auto insertResultPair = registration->bundleServiceInstance.insert(std::make_pair(bundle, s));
+    s = insertResultPair.first->second;
```
Comment (saschazelzer) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: The original code had a comment about discarding a newly created service instance in case of a race here. It would probably be good to have that comment back in.

Comment (jeffdiclemente) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: sure. will do.

File: framework/src/service/ServiceReferenceBasePrivate.cpp (hunk 11 above)
Comment (jeffdiclemente) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: I agree, it is a strange yet possible scenario. 

If one thread has a null service object and another has a valid service object, what happens all depends on which thread enters the lock first.

If a service factory does return a null service object, I don't feel its the Framework's responsibility to try and guarantee that a valid one is always returned (excluding cases where one exists in the cache already). If a client's service factory returns a null service object on one thread and then a valid one on another, that seems like a bug; either with the client code querying for the service object or the client's service factory implementation. 

I'm not sure how the else condition really helps ensure that a non-null service is returned. This feels like we're overcompensating for possible bugs in client code. To check in an else branch we still have to hold the lock.

Comment (saschazelzer) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: I agree that we cannot control the order, but we do not have to. The only case I think we should cover is that if we get a null service but have a non-null service cached because of a race, return the non-null service (just because we can). A service factory is allowed to return null and there is nothing we can do against that.

Comment (jeffdiclemente) [inline framework/src/service/ServiceReferenceBasePrivate.cpp]: Ok. That case sounds reasonable to me. I'll make the change.
