### PR TITLE
fix segfault when service class ctor throws

### LINKED ISSUE #585: segfault when a DS service configuration implements Activate/Deactivate methods and the service impl ctor throws
reproduction steps:
- create a DS bundle which implements a service, `foo` that throws in its constructor
- implement the `Activate` and `Deactivate` methods for the `foo` service configuration
- call `GetService` for a 'foo` service
- a segfault should occur

The failure is caused by not checking for a valid service object pointer when calling `Activate` or `Deactivate`.

### PR DESCRIPTION
**Pull request by jeffdiclemente**
Fixes #585 

Signed-off-by: The MathWorks, Inc. <jdicleme@mathworks.com>

### CODE REVIEW

**Review by achristoforides — APPROVED** [review]

**Comment by jeffdiclemente** [comment]
travis build failures are fixed in PR #588

**Review by carneyweb — APPROVED** [review]
Ship it.

**Review by kevinleeMW — APPROVED** [review]

File: compendium/DeclarativeServices/src/manager/ComponentConfigurationImpl.cpp [hunk 1]
```diff
@@ -445,12 +445,32 @@ ComponentConfigurationImpl::CreateAndActivateComponentInstanceHelper(
...
   try {
-    componentInstance->CreateInstanceAndBindReferences(ctxt);
+    componentInstance->CreateInstance(ctxt);
   } catch (const std::exception&) {
     logger->Log(
       cppmicroservices::logservice::SeverityLevel::LOG_ERROR,
-      "Exception while creating component instance and binding references.",
+      "Exception while creating component instance.",
+      std::current_exception());
+    throw;
```
Comment (pelliott-mathworks) [inline compendium/DeclarativeServices/src/manager/ComponentConfigurationImpl.cpp:460]: Just wondering if it's okay to leave the ComponentConfigurationImpl object in the state it's in. Maybe this component should be disabled since it can't be constructed?

**Review by pelliott-mathworks — APPROVED** [review]

File: compendium/DeclarativeServices/src/manager/ComponentConfigurationImpl.cpp (hunk 1 above)
Comment (jeffdiclemente) [reply compendium/DeclarativeServices/src/manager/ComponentConfigurationImpl.cpp:460]: The OSGi spec doesn't make any assertion about moving the state to disabled. The state will remain in satisfied and never move to active.
